### ISSUE TITLE
Conteo de carros

### ISSUE THREAD

**Issue by jerickvasquez** [puigalex/deteccion-objetos-video#13]
Hola Alex, espero te encuentres super bien, hay alguna manera de poder hacer el conteo de vehículos que se este detectando en en el video ?

**Comment by puigalex** [comment]
Sobre el output que genera el modelo (Lo que se está imprimiento den la terminal) puedes hacer un count sobre los elementos que tengan la etiqueta que te interesa, en este caso, vehiculos.

**Comment by puigalex** [comment]
Not an issue or bug
