### ISSUE TITLE
detect.py

### ISSUE THREAD

**Issue by NachoBosch** [puigalex/deteccion-objetos-video#3]
Encontré un error en el código de detect.py para poder usarlo.
Acá les dejo la corrección que le hice desde la línea 142 aprox, por las dudas.
Saludos ;)
-----------
        print("PATH",path)
        name=os.path.basename(path)
        print("NAME",name)
        plt.axis("off")
        plt.gca().xaxis.set_major_locator(NullLocator())
        plt.gca().yaxis.set_major_locator(NullLocator())
        filename = path.split("/")[-1].split(".")[0]
        #plt.savefig(f"output{filename}.jpeg", bbox_inches="tight", pad_inches=0.0)
        plt.savefig(f"output/"+name, bbox_inches="tight", pad_inches=0.0)
        plt.close()

**Comment by puigalex** [comment]
Muchas gracias @NachoBosch voy a revisarlo para integrarlo al código.
