### ISSUE TITLE
Problema con el comando labelImg

### ISSUE THREAD

**Issue by Vladinomio** [puigalex/deteccion-objetos-video#34]
Hola que tal, tengo un problema al llamar el comando labelImg me dice que no es posible abrirlo porq no se pueden iniciar los complementos Qt. Me pueden brindar una solución, gracias.
![Captura de pantalla de 2021-08-25 18-46-10](https://user-images.githubusercontent.com/89130024/130878912-556a5910-a099-4874-9646-238f0d80b178.png)

**Comment by AlbertoPerezGant** [comment]
Yo lo he hecho con Windows y en principio me permite generar los archivos necesarios

**Comment by Vladinomio** [comment]
Vale, lo voy a intentar

**Comment by Vladinomio** [comment]
Gracias

**Comment by Vladinomio** [comment]
Al final solo instale Qt Creator
