### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by NachoBosch** [puigalex/deteccion-objetos-video#4]
Hola Alex! tngo problemas para correr el entrenamiento porque train.py importa utils, que a su vez usa tensorflow! Y en mi laptop con Windows 10 no puedo hacer correr Tensorflow.
Me darías una mano para saber como correr el train de abajo pero en colab.
"python train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data --pretrained_weights weights/darknet53.conv.74 --batch_size 0.5"

Saludos

**Comment by puigalex** [comment]
Hola Nacho, 

Puede ser que el batch_size no es un numero entero, intentalo poner en 1 y ver si corre.

**Comment by NachoBosch** [comment]
Hola @puigalex  gracias por responder! ya lo cambie y nada. Ahora me dice nadita jaja te copio la ultima linea donde se corta. (pd. estoy usando elije cuda y le puse un batch de 1). Muy raro que se corta solo.
**Ultimas lineas de warning de tf=1.13 y despues se sale**

C:\Users\admin\anaconda3\envs\amb3\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

(amb3) C:\Users\admin\Code\deteccion-objetos-video-2>

**Comment by billy-turambar** [comment]
Hola Nacho haz revisado si se instalo todas las paqueterias?
porque yo tambien uss windows 10 y no me instalaba torch con el archivo requirement.txt
tuve que instalarlo de manera manual
Un saludo

**Comment by NachoBosch** [comment]
Hola @billy-turambar! Si me paso lo mismo e instale algunas de manera manual. Pero se corta sin arrojarme ningun error o algo, es muy raro jaja! No se que estare haciendo mal! A ti te anduvo? yo use python 3.6 y tensorflow 1.13

**Comment by billy-turambar** [comment]
SI pude hacerlo funcionar, con 3000 imagenes.
en tu caso creo que solo te queda debuggear para ver donde se corta. prueba poniendo print.
