### ISSUE TITLE
Duda sobre las imagenes

### ISSUE THREAD

**Issue by billy-turambar** [puigalex/deteccion-objetos-video#7]
Buenas
las imagenes deben ser del mismo tamaño o de una calidad minima?
he entrenado para detencion de 2 clases por 200 epocas con 1200 imagenes y no tengo resultados

**Comment by puigalex** [comment]
Cual es la resolucion y dimensiones de las imagenes que usaste para el entrenamiento?
Te marca algun error en especifico?

**Comment by billy-turambar** [comment]
Pues la verdad tengo imagenes de todas dimensiones la descargue directo de google con una extension de google chrome.
No me ha dado ningun error a excepcion de un warning que aparace a ratos y que creo que es porque hay unas 10 imagenes con transparencia.
el loss en estos momentos que estoy corriendo mi epoca 234 esta en un 40% en 0, un 30% entre 1-2, otro 25% entre 3-9 y un 5% mayor a 10

**Comment by billy-turambar** [comment]
Gracias por la respuesta y la paciencia estoy siendo muy insistente con esto la verdad, pero me ha llegado a interesar bastante

**Comment by puigalex** [comment]
Ya tuviste resultados? Si te esta apareciendo la informacion del 'loss' es que ya se está entrenando bien. El tema de las transparencias no estoy seguro si genere algun problema.

**Comment by billy-turambar** [comment]
Hola estimado Alex, si ya obtuve resultados, cambie todas mis imagenes por otras de mayor calidad ademas aumente el numero de 1200 a 3000 con las mismas 200 epocas ya obtuve un resultado consistente. De hecho hoy presente mi examen basado en eso y me fue excelente lo monte en una API con Flask para una Aplicacion Web y poder administrar las detecciones y las grabaciones. y las certesas.
Gracias por todo. Y creo que voy a iniciar mi carrera en IA me ha fascinado
Saludos desde Bolivia.
