### ISSUE TITLE
Duda de funcionamiento

### ISSUE THREAD

**Issue by RonaldoSic** [puigalex/deteccion-objetos-video#8]
Hola @puigalex saludos!
Tengo una duda, quiero saber si es posible que este programa lo soporte una Raspberry, específicamente el modelo 4 con 2 GB de RAM, es que necesito controlar hardware con la información que obtengo del código, de ante mano gracias por el apoyo!!

**Comment by puigalex** [comment]
depende que tan rapido quieres que se generen las predicciones. El camino que he utilizado para hacer deteccion de objetos sobre una raspberry pi es usar tensorflow lite.

**Comment by RonaldoSic** [comment]
Gracias @puigalex, por la respuesta pues te comento más o menos lo que quiero hacer, es que quiero que al detectar los objetos que necesito que por cierto ya empecé hacer el entrenamiento para detectar los objetos, los objetos estarán en una plataforma con un motor al encontrarlos necesito activar ese motor y pues poder trasladar ese objeto a otro lado por medio del motor y después que se ha detectado por el programa. Pero considero que la detección que necesito no es tan rápida.  Gracias por la respuesta!!

**Comment by puigalex** [comment]
Que bueno que te corrio, para optimizar la velocidad podrías intentar tambien otras soluciones como tensorflow lite
